In [1]:
from tennis_data_pipeline.loader.uk import load_clean_uk_atp_year
from tennis_data_pipeline.handler.uk.cleaner.tournaments import build_uk_tournament_table

df = load_clean_uk_atp_year(2023)
result = build_uk_tournament_table(df)
tournaments, inconsistencies = result.tournaments, result.inconsistencies

display(list(tournaments.columns))

['tour',
 'year',
 'uk_tournament_id',
 'location',
 'tournament_name',
 'series',
 'surface',
 'best_of',
 'is_outdoor',
 'start_date',
 'end_date',
 'num_matches',
 'num_rounds',
 'num_awarded_matches',
 'num_completed_matches',
 'num_retired_matches',
 'num_walkover_matches',
 'num_players',
 'champion',
 'runner_up',
 'champion_avg_rank',
 'champion_avg_odds']

In [4]:
inconsistencies

Empty DataFrame
Columns: [tournament_name, series, surface, best_of, is_outdoor]
Index: []

In [5]:
tournaments

,tour,year,uk_tournament_id,location,tournament_name,series,surface,best_of,is_outdoor,start_date,...,num_rounds,num_awarded_matches,num_completed_matches,num_retired_matches,num_walkover_matches,num_players,champion,runner_up,champion_avg_rank,champion_avg_odds
0,atp,2023,1,Adelaide,Adelaide International 1,atp_250,hard,3,True,2023-01-01,...,5,0,28,3,0,32,Djokovic N.,Korda S.,5.0,1.176000
1,atp,2023,2,Pune,Maharashtra Open,atp_250,hard,3,True,2023-01-02,...,5,0,26,0,1,28,Griekspoor T.,Bonzi B.,95.0,2.120000
2,atp,2023,3,Adelaide,Adelaide International 2,atp_250,hard,3,True,2023-01-09,...,5,0,27,0,0,28,Kwon S.W.,Bautista Agut R.,84.0,2.448000
3,atp,2023,4,Auckland,ASB Classic,atp_250,hard,3,True,2023-01-08,...,5,0,25,1,1,28,Gasquet R.,Norrie C.,67.0,2.006000
4,atp,2023,5,Melbourne,Australian Open,grand_slam,hard,5,True,2023-01-16,...,7,0,126,1,0,128,Djokovic N.,Tsitsipas S.,5.0,1.115714
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,atp,2023,60,Vienna,Vienna Open,atp_500,hard,3,False,2023-10-23,...,5,0,30,1,0,32,Sinner J.,Medvedev D.,4.0,1.408000
61,atp,2023,61,Paris,BNP Paribas Masters,masters_1000,hard,3,False,2023-10-30,...,6,0,53,0,2,56,Djokovic N.,Dimitrov G.,1.0,1.224000
62,atp,2023,62,Metz,Open de Moselle,atp_250,hard,3,False,2023-11-05,...,5,0,26,1,0,28,Humbert U.,Shevchenko A.,23.0,1.280000
63,atp,2023,63,Sofia,Sofia Open,atp_250,hard,3,False,2023-11-07,...,5,0,26,1,0,28,Mannarino A.,Draper J.,25.0,1.767500
64,atp,2023,64,Turin,Masters Cup,tour_finals,hard,3,False,2023-11-12,...,3,0,14,1,0,9,Djokovic N.,Sinner J.,1.0,1.385000